//authentication
export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE";

export const AUTH_REGISTER = "AUTH_REGISTER";
export const AUTH_REGISTER_SUCCESS = "AUTH_REGISTER_SUCCESS";
export const AUTH_REGISTER_FAILURE = "AUTH_REGISTER_FAILURE";

export const AUTH_GET_STATUS = "AUTH_GET_STATUS";
export const AUTH_GET_STATUS_SUCCESS = "AUTH_GET_STATUS_SUCCESS";
export const AUTH_GET_STATUS_FAILURE = "AUTH_GET_STATUS_FAILURE";

export const AUTH_EDIT_USERINFO ="AUTH_EDIT_USERINFO";
export const AUTH_EDIT_USERINFO_SUCCESS = "AUTH_EDIT_USERINFO_SUCCESS";
export const AUTH_EDIT_USERINFO_FAILURE = "AUTH_EDIT_USERINFO_FAILURE";

export const AUTH_LOGOUT = "AUTH_LOGOUT";


//image
export const IMAGE_GET = "IMAGE_GET";
export const IMAGE_GET_SUCCESS ="IMAGE_GET_SUCCESS";
export const IMAGE_GET_FAILURE ="IMAGE_GET_FAILURE";
export const IMAGE_GET_SEARCH_SUCCESS = "IMAGE_GET_SEARCH_SUCCESS";

export const IMAGE_SEARCHNAME_SET = "IMAGE_SEARCHNAME_SET";

//image Download
export const IMAGE_DOWNLOAD = "IMAGE_DOWNLOAD";
export const IMAGE_DOWNLOAD_SUCCESS = "IMAGE_DOWNLOAD_SUCCESS";
export const IMAGE_DOWNLOAD_FAILURE = "IMAGE_DOWNLOAD_FAILURE";

//image save to server
export const IMAGE_SAVETO_SERVER = "IMAGE_SAVETO_SERVER";
export const IMAGE_SAVETO_SERVER_SUCCESS = "IMAGE_SAVETO_SERVER_SUCCESS";
export const IMAGE_SAVETO_SERVER_FAILURE = "IMAGE_SAVETO_SERVER_FAILURE";

//User image info
export const USER_GET_IMAGEINFO = "USER_GET_IMAGEINFO";
export const USER_GET_IMAGEINFO_SUCCESS = "USER_GET_IMAGEINFO_SUCCESS";
export const USER_GET_IMAGEINFO_FAILURE = "USER_GET_IMAGEINFO_FAILURE";

export const USER_SAVE_IMAGEINFO = "USER_SAVE_IMAGEINFO";
export const USER_SAVE_IMAGEINFO_SUCCESS = "USER_SAVE_IMAGEINFO_SUCCESS";
export const USER_SAVE_IMAGEINFO_FAILURE = "USER_SAVE_IMAGEINFO_FAILURE";

export const USER_DEL_IMAGEINFO = "USER_DEL_IMAGEINFO";
export const USER_DEL_IMAGEINFO_SUCCESS = "USER_DEL_IMAGEINFO_SUCCESS";
export const USER_DEL_IMAGEINFO_FAILURE = "USER_DEL_IMAGEINFO_FAILURE";

export const USER_GET_ALL_IMAGEINFO = "USER_GET_ALL_IMAGEINFO";
export const USER_GET_ALL_IMAGEINFO_SUCCESS = "USER_GET_ALL_IMAGEINFO_SUCCESS";
export const USER_GET_ALL_IMAGEINFO_FAILURE = "USER_GET_ALL_IMAGEINFO_FAILURE";

export const IMAGE_GET_USER_SUCCESS = "IMAGE_GET_USER_SUCCESS";
